name: Build and Test with Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        source venv/bin/activate
        python your_script.py  # Replace this with your specific Python script

    - name: Build Jekyll site
      run: |
        source venv/bin/activate
        jekyll build

    - name: List virtual environment
      run: ls venv/bin

    - name: Check installed packages
      run: |
        source venv/bin/activate
        pip freeze

