name: Build and Test with Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Install dependencies
      run: venv/bin/pip install -r requirements.txt

    - name: Run Python Script
      run: venv/bin/python your_script.py  # Replace this with your specific Python script

    - name: Build Jekyll site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

    - name: List virtual environment
      run: ls venv/bin

    - name: Check installed packages
      run: venv/bin/pip freeze
